### ISSUE TITLE
JupyterLab does not correctly show the function application $ operator in several instances in Lesson 5

### ISSUE THREAD

**Issue by dbachy** [input-output-hk/haskell-course#26]
There are instances where the following is incorrectly reflected in Binder: "@@0@@" 
For example, this is shown: f @@0@@ h x  =  f (g (h x))
Instead of this: f $ g $ h x = f (g (h x))
See enclose screenshot:
<img width="1528" alt="Screen Shot 2022-12-13 at 4 35 17 PM" src="https://user-images.githubusercontent.com/69743809/207475581-c2db4c73-0d30-4795-a29a-d374238712fb.png">

**Comment by rober-m** [comment]
Fixed, thank you! 😃
