### ISSUE TITLE
Bug in last exercise on lesson 6 Homework

### ISSUE THREAD

**Issue by SatoshiNakamotoUY** [input-output-hk/haskell-course#32]
I think the filtering is applied to the wrong list, it should filter "bevogBeerPrices" with orderList", it's doing the opposite as it is right now

It works as it is now because the "orderList" has only the first three types of beers but won't work for other order lists.

Example: if we change orderList so it is
  orderList = 
    [ ("Tak", 5),
      ("Kramah", 4),
      ("_Baja_", 7)
    ]

Then answer should be 8.5+(5*6+4*7+7*7.5)=119
beerCosts orderList gives = 126 as it zips "Ond" cost with # of Baja beers ordered.

Solution proposal:

    `beerCosts orderlst =
      foldr (+) deliveryCost
     . zipWith (*) (map snd orderlst) 
     . map snd
     $ filter (\name -> fst name `elem` map fst orderlst) bevogBeerPrices`

Enclosed pdf file with handwritten comments on VSCode might help!

[Lesson 6 Homework Solution Bug.pdf](https://github.com/input-output-hk/haskell-course/files/11302246/Lesson.6.Homework.Solution.Bug.pdf)

**Comment by rober-m** [comment]
Thank you for the report! 🙌 I changed the question when reported, but forgot to close the issue 😅
