### ISSUE TITLE
Free Online Integrated Development And Education Environment (IDEE) For Cardano To Grow The Community

### ISSUE THREAD

**Issue by johnshearing** [input-output-hk/haskell-course#6]
I am grateful for the [invitation to make requests about the course](https://github.com/input-output-hk/haskell-course/blob/main/FAQ.md).

First, congratulations to Robertino Martinez for being the very first to write Haskell course material that I can actually follow. I have tried and failed to understand Haskell using all the [Haskell courses listed in this index](https://johnshearing.github.io/cardano_syllabus/). So if Robertino has found a way to teach me, then he has found a way to teach everyone. And that is exactly who we want joining the Cardano developer community - everyone.

I have the distinction of having failed the Plutus Pioneers program all 3 times.
I failed each time because I was never able to setup my development environment. 
[I am not the only one who had this problem.](https://www.youtube.com/watch?v=NSSbIMQaXM0&t=412s)
There must be many like me who have failed before even getting started.

On joining the Marlowe Pioneers I received extensive help from the community and was able to setup the development environment well enough to participate. Then with much help from our teacher Brian Bush I was able to understand the lessons and contribute in small ways.

([Brian presents his lessons using Jupyter Notebook](https://github.com/input-output-hk/marlowe-cardano/tree/main/marlowe-cli/lectures#lectures-on-marlowe-cli))
[In this video](https://youtu.be/DmF7dIKmJMo) you can see Brian generating and running smart contracts on the testnet using Jupyter notebooks.

Despite many attempts, I was never able to run Brian's lessons from Jupyter Notebook. Instead I was forced to cut and paste mountains of code from the notebooks into my local terminal window. This extra step was inefficient and very error prone. As far as I know, none of the other students were able to run the code from Jupyter Notebook either. Something about our local environments were different from Brian's

Robertino has clearly solved the setup problem by using a version of Jupyter that runs in the cloud.

In summary:
[In this video](https://youtu.be/DmF7dIKmJMo), Brian has demonstrated the advantages of generating and running Cardano smart contracts from Jupyter.
Robertino has demonstrated that he can distribute to all a cloud version of Jupyter that we know will work because it runs with no install or local complications.
We know we are losing developers before they even arrive because it is so difficult to setup the development environment.

**Ask Number One**
**Please, can Robertino's Haskell lessons in Jupyter be expanded to include Plutus and Marlowe such that we can query and deploy to the testnet right from the lesson materials the way we see Brian doing it?**

Aside from providing course materials in Jupyter, Robertino has also provided us with an [online version of the VS Code IDE](https://gitpod.io/#https://github.com/rober-m/haskell-bootcamp) which hosts Jupyter. When I saw that I thought "Oh My God!, [That's Remix for Cardano](https://youtu.be/gyMwXuJrbJQ?t=7421)"
Remix is Ethereum's free online integrated development and education environment (IDEE).
It's the gateway drug to Ethereum smart contract development.
Anyone with access to the Internet can go to https://remix.ethereum.org/ to learn Solidity and then deploy a smart contract for free (not counting the enormous transaction fees)
We need that too!

[Robertino's online VS Code implementation](https://gitpod.io/#https://github.com/rober-m/haskell-bootcamp) has something that Remix does not have -  Jupyter.
Well it almost has Jupyter. It displays Jupyter but sadly it doesn't run it. 
That's because the online VS Code implementation is not free after 50 hours and Robertino wants users to have the service available for the lesson homework.

**Ask Number Two**
**Please, Give us a free IDEE for Cardano like [Remix](https://remix.ethereum.org/) but that also runs Jupyter.
You are so close. Please, you are almost there.**

**Ask Number Three**
Finally, when Robertino's lessons are all recorded, May we please see the lessons in one giant video on FreeCodeCamp much like [this one for Remix](https://youtu.be/gyMwXuJrbJQ?t=7421) which is 32 hours long and has been view more than 800,000 times? That will bring more developers to Cardano as they learn to love Haskell, Plutus, and Marlowe.

Much thanks for considering all these requests.

**Comment by rober-m** [comment]
Hi @johnshearing! Thank you so much for your kind words!! I'm glad that you liked my previous and this course! 😃 (Impressive list of resources, btw.) Luckily, now I'm working with really smart people, so I'm hoping this course will be even better!

About your questions. Next week we'll have a few meetings to determine the education team's objectives and priorities. I, of course, will be working on this course. But we also have plans to build on top of what I did for this course's environment for the next PPP. (And other projects.)

After these meetings, I'll come back to this issue and answer your questions with more certainty!

Thank you again for your kind words and your feedback!! 🙌😄

**Comment by rober-m** [comment]
Hi @johnshearing! I'm back! 😂

First of all, thank you again for your kind and encouraging words! I'm delighted to be able to help you as you described!

About your questions:
- Asks numbers one and two are in the works for the next PPP! 💪 Our engineers are working really hard on improving the blockchain itself and Plutus, so they won't be able to finish something like Remix on time for the next PPP. BUT! We're working on a partnership with another company in the ecosystem to do just that! 😁 We have to iron out the details, but I'm confident we'll be able to deliver something exactly or pretty close to what you're asking for! 🎉🎉
- I'd love to put the course on FreeCodeCamp! Once it's done, I'll reach out to them to see if we can make it happen!

If you have any other concerns, don't hesitate and comment here or open another issue!! Hope you're still learning a ton! I'll see you in the next lesson! 😃

**Comment by johnshearing** [comment]
Thank you so much Robertino to you and IOG for granting my requests.
I am certain this is going to enormously increase the size of the developer community and the ways in which people use Cardano infrastructure.

And yes, I am still learning a ton from your course. Can't wait for the next lesson.
Thanks so much for opening the door to Haskell for the rest of us.

**Comment by adulphan** [comment]
@rober-m 
There are projects (like Sundaeswap, JPG.store, etc) currently running on Cardano. I can imagine they already developed in-house IDE or something similar. Can you reach out and form some kind of co-development of a Cardano IDE to be share with the ecosystem? That would speed things up immensely. Developers, especially new ones wanting to get into Cardano, desperately need the IDE. Most of them can't wait months. This is urgent. Make it happens before they go build elsewhere.

Please see:

https://forum.cardano.org/t/developers-are-having-dismal-experience-building-on-cardano/110080

**Comment by rober-m** [comment]
Answer in issue #23
